### ISSUE TITLE
Endpoint links broken in documentation

### ISSUE THREAD

**Issue by jczaplew** [ePandda/ePandda-API#30]
On the [documentation page](https://epandda.org/#documentation) the endpoint links are broken. It appears the issue is that the `href` does not include a protocol, so the browser prepends the domain the request is coming from.

For example, the endpoint `api.epandda.org/publications` has an `href` of `api.epandda.org/publications`, which results in the browser redirecting to `https://epandda.org/api.epandda.org/publications`

**Comment by collectiveaccess** [comment]
Fixed.
